name: MD to PDF & DOCX

on:
  push:
    paths:
      - "docs/**/*.md"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-recommended texlive-fonts-recommended texlive-xetex

      - name: Convert Markdown to PDF/DOCX
        run: |
          mkdir -p docs/outputs
          mapfile -t files < <(git ls-files "docs/**/*.md")
          for f in "${files[@]}"; do
            base="$(basename "$f" .md)"
            outdir="docs/outputs"
            pandoc "$f" -o "$outdir/$base.pdf" --pdf-engine=xelatex
            pandoc "$f" -o "$outdir/$base.docx"
          done

      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(docs): gerar PDF/DOCX a partir de Markdown"
          file_pattern: docs/outputs/*
